### ISSUE TITLE
[enchancement] Perfomance.

### ISSUE THREAD

**Issue by shockpast** [thecraftianman/SimpleArmorDisplay#1]
- [`if not visEnt:Alive() then return end`](https://github.com/thecraftianman/SimpleArmorDisplay/blob/725c2e2ac3f646f3e198146967c761d7d006b2fc/lua/autorun/client/simple_armor_display.lua#L15) is works significantly slower than `if visEnt:Health() <= 0 then return end`

**Comment by thecraftianman** [comment]
Thanks, I'll fix that.
